session_name: django-channels-graphql-ws
start_directory: ./ # load session relative to config location (project root).
shell_command_before:
- '[ -f .venv/bin/activate ] && source .venv/bin/activate && reset'
windows:
- window_name: django-channels-graphql-ws
  focus: True
  layout: main-horizontal
  options:
    main-pane-height: 67%
  panes:
  - focus: true
  - pane 
  - make watch_mypy
  - make watch_test
